import { defineConfig } from "tsup";

export default defineConfig({
  entry: ["apps/api/src/index.ts"],
  format: ["esm"],
  platform: "node",
  target: "node20",
  outDir: "apps/api/dist",
  outExtension: () => ({ js: ".js" }),
  sourcemap: true,
  clean: true,
  dts: false,
  splitting: false,
  bundle: true,
  // Bundle EVERYTHING into a single self-contained file for Vercel
  // This ensures all dependencies are included and no module resolution issues occur
  noExternal: [/.*/],
  // Only mark Node.js built-ins as external
  external: [
    "node:*",
    "fs",
    "path",
    "os",
    "crypto",
    "stream",
    "util",
    "events",
    "buffer",
    "http",
    "https",
    "url",
    "querystring",
    "zlib",
    "net",
    "tls",
    "child_process",
    "worker_threads",
    "async_hooks",
    "perf_hooks",
    "dns",
    "assert",
    "timers",
    "tty",
    "readline",
  ],
});
